name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  build-leak_oracle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build leak_oracle
        working-directory: ./leak_oracle
        run: |
          make install
          make build

  build-leak_provisionner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build leak_provisionner
        working-directory: ./leak_provisionner
        run: |
          make install
          make build

  test-leak_oracle:
    runs-on: ubuntu-latest
    needs: build-leak_oracle
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Test leak_oracle
        working-directory: ./leak_oracle
        run: make test-integration-ci

  test-leak_provisionner:
    runs-on: ubuntu-latest
    needs: build-leak_provisionner
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Test leak_provisionner
        working-directory: ./leak_provisionner
        run: make test-integration-ci